# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
import numpy as np
s=np.zeros(10)
print(s)
s.size

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np
p=np.array([[2,3,4,8,10],[5,6,7,9,8]])
print(p)
print(p.size,p.itemsize)

[[ 2  3  4  8 10]
 [ 5  6  7  9  8]]
10 8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
m=np.zeros(10)
m[4]=1
print(m)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = 10 + np.arange(40)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
import numpy as np
m=np.array([1,2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100])
print(m)
n =m[::-1]
print(n)

[  1   2   3   4   5   6   7   8   9  10  20  30  40  50  60  70  80  90
 100]
[100  90  80  70  60  50  40  30  20  10   9   8   7   6   5   4   3   2
   1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
import numpy as np
o=np.arange(9).reshape((3,3))
print(o)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
i=np.array([1,2,0,0,4,0])

o=np.nonzero(i)
print(o)

(array([0, 1, 4]),)


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
o=np.eye(3,3)
print(o)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
l=np.random.random((3,3,3))
print(l)

[[[0.64235373 0.13029168 0.71061712]
  [0.02355249 0.40464404 0.18680247]
  [0.04765758 0.67937551 0.39794612]]

 [[0.97392229 0.85240289 0.09647802]
  [0.50691985 0.25493239 0.73180787]
  [0.4605062  0.5500566  0.51856954]]

 [[0.13171853 0.79645182 0.26762063]
  [0.60610864 0.18925648 0.34916637]
  [0.54987648 0.97319782 0.2537935 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
n=np.random.random((10,10))
print(n)
min,max=n.min(),n.max()
print(min,max)

[[0.84113315 0.3117969  0.37098548 0.76900928 0.06430005 0.36861357
  0.08684308 0.83181602 0.06366455 0.03081406]
 [0.46315201 0.22173665 0.59502545 0.91504524 0.45038339 0.78392916
  0.3110074  0.41639784 0.97362927 0.30933205]
 [0.8230574  0.52334504 0.15233563 0.38252184 0.8452272  0.51971746
  0.14750724 0.63265697 0.78697307 0.01427819]
 [0.6477962  0.53368544 0.85636897 0.83242965 0.73359498 0.34605297
  0.68120041 0.72338862 0.43723735 0.90383184]
 [0.41920496 0.04291109 0.08635864 0.30867789 0.19718518 0.90405181
  0.0929715  0.75052551 0.26655037 0.18854378]
 [0.66714421 0.26077997 0.21320451 0.42646073 0.19803502 0.72874312
  0.24867712 0.296488   0.88461583 0.7036847 ]
 [0.1798793  0.75930231 0.48769105 0.16739693 0.83678265 0.67755772
  0.515629   0.44163162 0.44123115 0.38567015]
 [0.05743589 0.49883744 0.6663844  0.03813615 0.53887041 0.28091944
  0.96175228 0.01965971 0.2941145  0.11865781]
 [0.86877383 0.23730059 0.14321534 0.50965765 0.47708571 0.89328093
  0.75514173

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
m=np.random.random(30)
print(m)
mean=m.mean()
print(mean)

[0.90469052 0.75469328 0.36560304 0.44946448 0.83317187 0.48740965
 0.92139573 0.38028738 0.28890545 0.88788    0.29230565 0.02124496
 0.24204376 0.40603861 0.63133683 0.81509349 0.32279695 0.74304644
 0.61413223 0.20583441 0.10119874 0.86334261 0.59063123 0.57925792
 0.29837223 0.79313098 0.23671595 0.14431633 0.92634563 0.20659919]
0.5102428513506724


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
b=np.ones((5,5))
b[1:-1,1:-1]=0
print(b)          

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [23]:
a=np.arange(1,13).reshape(3,4)
b=np.pad(a,pad_width=1,mode="constant",constant_values=0)
b

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [24]:
0*np.nan,np.nan == np.nan,np.inf > np.nan,np.nan - np.nan,0.3 == 3 * 0.1

(nan, False, False, nan, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [26]:
x=np.eye(5,5)
y=np.diag([1,2,3,4])
y=np.insert(y,4,np.zeros(y.shape[1]),axis=1)
y=np.insert(y,0,np.zeros(x.shape[0]),axis=0)
x+y

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [27]:
x=np.zeros(64).reshape(8,8)
x[::2,::2]=1
x[1::2,1::2]=1
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [28]:
x=np.arange(336).reshape(6,7,8)
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [29]:
x=np.tile(np.array([[1,0],[0,1]]),[4,4])
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [30]:
df=np.random.random((5,5))
dfmin,dfmax=df.min(),df.max()
df=(df-dfmin)/(dfmax-dfmin)
df

array([[0.91880313, 0.44190522, 0.15575824, 0.40862432, 0.08874991],
       [0.40948322, 0.90410849, 0.27069585, 0.24469876, 0.66425565],
       [0.45529581, 0.14912088, 0.74568368, 1.        , 0.50741633],
       [0.91752995, 0.020855  , 0.        , 0.78566535, 0.45330841],
       [0.84781122, 0.27026124, 0.90219445, 0.88773432, 0.91853744]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [33]:
mat1=np.random.randint(2,10,(5,3))
mat2=np.random.randint(2,10,(3,2))
x=np.dot(mat1,mat2)
x

array([[63, 60],
       [84, 81],
       [66, 65],
       [99, 90],
       [70, 70]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [34]:
x=np.arange(20)
x[(x>3) & (x<=8)]*=-1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [35]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [36]:
x=np.arange(12).reshape(3,4)
print(x)
print(x**x)
print(2 << x >> 2)
print(x<-x)
print(1j*x)
print(x/1/1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[           1            1            4           27]
 [         256         3125        46656       823543]
 [    16777216    387420489  10000000000 285311670611]]
[[   0    1    2    4]
 [   8   16   32   64]
 [ 128  256  512 1024]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[0. +0.j 0. +1.j 0. +2.j 0. +3.j]
 [0. +4.j 0. +5.j 0. +6.j 0. +7.j]
 [0. +8.j 0. +9.j 0.+10.j 0.+11.j]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [37]:
print(np.array(0)/ np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [38]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)),x)

array([ -3.,  -6.,  -9., -10.,  -3.,   6.,  -3.,   8.,   4.,  -6.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [39]:
x=np.arange(0,10)
Y=np.arange(8,19)
Z=np.intersect1d(x,Y)
Z

array([8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [40]:
np.seterr(all='ignore')
X=np.arange(3)/0
with np.errstate(divide='warn'):
     X=np.arange(3)/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [41]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [42]:
Today=np.datetime64('today','D')
print('Today : ',Today)
Yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print('Yesterday : ',Yesterday)
Tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print('Tomorrow : ',Tomorrow)

Today :  2022-11-30
Yesterday :  2022-11-29
Tomorrow :  2022-12-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [43]:
X=np.arange('2016-07','2016-08',dtype='datetime64[D]')
X

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [44]:
A=np.ones(5)
B=np.ones(5)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=A)

array([-1., -1., -1., -1., -1.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [45]:
X=np.random.uniform(0,12,10)
print(X)
print(X-(X%1))
print(np.floor(X))
print(np.ceil(X)-1)
print(X.astype(int))
print(np.trunc(X))

[2.28553121 8.50475343 3.85178747 1.9577548  5.4602242  5.48267655
 3.44776878 1.94455068 4.49741474 7.47747974]
[2. 8. 3. 1. 5. 5. 3. 1. 4. 7.]
[2. 8. 3. 1. 5. 5. 3. 1. 4. 7.]
[2. 8. 3. 1. 5. 5. 3. 1. 4. 7.]
[2 8 3 1 5 5 3 1 4 7]
[2. 8. 3. 1. 5. 5. 3. 1. 4. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [46]:
x=np.zeros((5,5))
x+=np.arange(0,5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [47]:
def generate():
     for x in range(10):
         yield x

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [49]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [50]:
x=np.random.randint(23,78,10)
print(x)
np.sort(x)

[54 63 67 32 63 56 64 77 73 29]


array([29, 32, 54, 56, 63, 63, 64, 67, 73, 77])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [51]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

8.860588073730469
2.886056900024414


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [52]:
x=np.random.randint(0,2,5)
y=np.random.randint(0,2,5)
z=np.array_equal(x,y)
print(z)
z=np.allclose(x,y)
print(z)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [53]:
x=np.random.randint(12,24,50)
x.flags.writeable=True
x[1]=2

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [54]:
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[1.01478948 0.36059223 0.17701158 0.91070854 1.03556346 0.3444457
 1.00673219 1.14229322 0.56242332 0.94616527]
[1.14106943 0.24533588 0.05075704 1.43060725 0.2984786  0.07282732
 0.46189192 0.85314796 0.72284269 1.03165798]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [56]:
x=np.random.random(10)
print(x)
n=np.argmax(x)
x[n]=0
x

[0.12511015 0.39312058 0.02333238 0.07456095 0.36837795 0.62886951
 0.69258576 0.34764635 0.49624166 0.04161886]


array([0.12511015, 0.39312058, 0.02333238, 0.07456095, 0.36837795,
       0.62886951, 0.        , 0.34764635, 0.49624166, 0.04161886])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [58]:
k = np.zeros((5,5), [('x',float),('y',float)])
k['x'],k['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [59]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [61]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [60]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [62]:
x = np.arange(100)
print("array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
6.443801867072696
6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [63]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [64]:
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
d

array([[0.        , 0.36870947, 0.95425609, 0.29281379, 0.68615011,
        0.70434408, 0.89039685, 0.5431027 , 0.26450691, 0.57626196],
       [0.36870947, 0.        , 0.79781943, 0.66146652, 0.88789161,
        0.69828774, 0.77216835, 0.78731482, 0.24416023, 0.65369115],
       [0.95425609, 0.79781943, 0.        , 1.14450411, 0.81360186,
        0.37351338, 0.10541597, 0.86476088, 0.69899893, 0.53999791],
       [0.29281379, 0.66146652, 1.14450411, 0.        , 0.63441426,
        0.82828927, 1.06332696, 0.47254246, 0.51879146, 0.6642901 ],
       [0.68615011, 0.88789161, 0.81360186, 0.63441426, 0.        ,
        0.44361619, 0.70871323, 0.16188649, 0.64373936, 0.30879416],
       [0.70434408, 0.69828774, 0.37351338, 0.82828927, 0.44361619,
        0.        , 0.27085808, 0.49345393, 0.50162256, 0.17431345],
       [0.89039685, 0.77216835, 0.10541597, 1.06332696, 0.70871323,
        0.27085808, 0.        , 0.76389894, 0.64437684, 0.44077258],
       [0.5431027 , 0.78731482, 0.8647608

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [65]:
x = np.arange(10, dtype=np.float32)
print(x)
x=x.astype(np.int32, copy=False)
x

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [67]:
Z = np.arange(9).reshape(3,3)
print(Z)
print("Using ndenumerate : \n", list(np.ndenumerate(Z)),'\n')
print("Using np.ndindex : \n")
l=[]
for index in np.ndindex(Z.shape):
    l.append((index, Z[index]))
print(l)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Using ndenumerate : 
 [((0, 0), 0), ((0, 1), 1), ((0, 2), 2), ((1, 0), 3), ((1, 1), 4), ((1, 2), 5), ((2, 0), 6), ((2, 1), 7), ((2, 2), 8)] 

Using np.ndindex : 

[((0, 0), 0), ((0, 1), 1), ((0, 2), 2), ((1, 0), 3), ((1, 1), 4), ((1, 2), 5), ((2, 0), 6), ((2, 1), 7), ((2, 2), 8)]


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [68]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [69]:
n = 9
p = 3
Z = np.zeros((n,n))
t= np.random.choice(range(n*n), p, replace=False)
np.put(Z,t,[33,55,78])
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 33.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 55.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 78.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [70]:
X = np.random.rand(5, 15)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.08720647,  0.07146957,  0.00137987,  0.24369408, -0.27142739,
         0.22150353,  0.3679425 , -0.2642276 , -0.04624062, -0.36798899,
         0.53943992, -0.34736711,  0.34470924, -0.33846723, -0.24162623],
       [-0.14609258, -0.10191967, -0.01094427, -0.29439869, -0.48755936,
         0.26934079,  0.10097681,  0.09751745, -0.40446411, -0.24451895,
        -0.02474935,  0.37343244,  0.13085671,  0.40412067,  0.3384021 ],
       [ 0.23994911,  0.45715962, -0.42909315, -0.45283293,  0.41846243,
         0.43604153, -0.048184  , -0.28088014,  0.1357007 , -0.46434004,
         0.14152873, -0.41372582,  0.46939635, -0.43513651,  0.22595412],
       [-0.3600213 , -0.18076928,  0.00067826,  0.02351831, -0.22286929,
        -0.43379222,  0.18062544,  0.28368837,  0.09175393,  0.34075588,
        -0.13851594,  0.27518492,  0.16983369,  0.03433029, -0.06440105],
       [ 0.35773759, -0.4748742 , -0.2063789 ,  0.49840957, -0.45039969,
         0.2661963 , -0.39643653,  0.25304846, 

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [71]:
A= np.random.randint(0,6,(3,3))
print(A,'\n')
print(A[:,1],"\n")
print(A[:,1].argsort(),"\n")
print(A[A[:,1].argsort()])

[[4 0 5]
 [5 5 2]
 [4 0 4]] 

[0 5 0] 

[0 2 1] 

[[4 0 5]
 [4 0 4]
 [5 5 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [72]:
Z = np.random.randint(0,5,(3,10))
print(Z,"\n")
print((~Z.any(axis=0)),"\n")
print((~Z.any(axis=0)).any())

[[1 4 3 3 2 1 1 4 2 0]
 [2 2 2 2 2 3 2 2 3 2]
 [3 2 3 0 0 0 4 4 2 3]] 

[False False False False False False False False False False] 

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [76]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.48844284904536395


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [77]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [78]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "Array1")
print (Z)

[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [79]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 4. 4. 3. 3. 2. 3. 1. 3. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [80]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [81]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [82]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[61 70 79 61]
 [66 49 53 48]
 [61 47 45 38]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [83]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)

D_counts = np.bincount(S)

D_means = D_sums / D_counts
print(D_means)

[0.4892114  0.65092621 0.45942337 0.59476289 0.39582237 0.55164875
 0.64177083 0.51322541 0.47746137 0.77543167]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [84]:
A = np.random.uniform(0,1,(4,4))
B = np.random.uniform(0,1,(4,4))

np.diag(np.dot(A, B))

array([0.46997131, 0.72940103, 0.63309089, 0.83888294])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [85]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [86]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [87]:
A = np.arange(25).reshape(5,5)
print(A,"\n")
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [88]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 54) ( 2, 72) ( 8, 55) ( 8, 60) ( 8, 77) ( 8, 79) (13, 14) (13, 32)
 (14, 32) (17, 39) (17, 92) (20, 69) (20, 70) (26, 41) (26, 77) (33, 42)
 (33, 62) (38, 76) (38, 82) (39, 92) (41, 77) (42, 62) (45, 54) (45, 67)
 (54, 67) (54, 72) (55, 60) (69, 70) (76, 82) (77, 79)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [89]:
C = np.bincount([1,1,2,3,4,4,6]) 
print(C)
print(np.arange(len(C)),"\n")
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6] 

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [90]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [91]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [92]:
Z = np.random.randint(0,2,100)
print(Z,"\n")
print(np.logical_not(Z, out=Z))

Z = np.random.uniform(-1.0,1.0,100)
print(Z)
np.negative(Z, out=Z)

[0 1 0 0 0 1 1 1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0 0
 1 1 1 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 0 1 1 1 0 0 1
 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1] 

[1 0 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1
 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 1 0
 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 0 1 1 0]
[ 0.38139675  0.43270507  0.54614945  0.90618717  0.07131561  0.26833628
  0.99343881  0.76935724  0.56043719  0.00947064 -0.08047913  0.83350794
 -0.84095359  0.4175835  -0.60803975 -0.8214182   0.16597263 -0.06616185
 -0.22008502 -0.59393743 -0.01172119 -0.9694233  -0.04386377  0.04526244
 -0.98955957  0.89808534 -0.20058982  0.85874088  0.83133616 -0.7725698
  0.0650617  -0.93694179  0.85855085 -0.27937962 -0.34532979  0.21110971
 -0.43343942  0.71830299 -0.87580354 -0.73421607  0.92255197 -0.46672168
 -0.86271208 -0.08852231 -0.14057578 -0.22222591  0.10353345 -0.43715547
 -0.329

array([-0.38139675, -0.43270507, -0.54614945, -0.90618717, -0.07131561,
       -0.26833628, -0.99343881, -0.76935724, -0.56043719, -0.00947064,
        0.08047913, -0.83350794,  0.84095359, -0.4175835 ,  0.60803975,
        0.8214182 , -0.16597263,  0.06616185,  0.22008502,  0.59393743,
        0.01172119,  0.9694233 ,  0.04386377, -0.04526244,  0.98955957,
       -0.89808534,  0.20058982, -0.85874088, -0.83133616,  0.7725698 ,
       -0.0650617 ,  0.93694179, -0.85855085,  0.27937962,  0.34532979,
       -0.21110971,  0.43343942, -0.71830299,  0.87580354,  0.73421607,
       -0.92255197,  0.46672168,  0.86271208,  0.08852231,  0.14057578,
        0.22222591, -0.10353345,  0.43715547,  0.32933008, -0.57862054,
        0.60798482,  0.62505595, -0.28729356, -0.43165302, -0.79379772,
       -0.38906109,  0.00462174, -0.83364937,  0.94046129,  0.15578789,
        0.13306785, -0.8320233 ,  0.59699886,  0.65281882, -0.20065476,
        0.68918578, -0.259772  , -0.24935425, -0.6984841 ,  0.62

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [93]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.99701846 11.23774599 12.09498335  4.61051727 13.23607817  5.88468398
  5.23320394  2.96165574  8.41345479  2.47413798]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [94]:
a= np.random.uniform(-10, 10, (10,2))
b = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(a,b,p_i) for p_i in p]))

[[8.58984488e+00 2.21552011e+00 7.22186078e+00 1.05497141e+00
  9.24712135e+00 2.49690213e+00 2.82356941e+00 3.17842620e+00
  2.02220193e+00 1.23819413e+01]
 [1.40419358e-02 4.28567384e+00 1.52098842e+00 8.61026684e+00
  2.77529102e-01 5.18648274e+00 5.93348269e+00 3.30813595e+00
  1.63453045e+00 2.57140045e+00]
 [6.81638842e+00 1.36856736e+00 5.84352057e+00 2.70786970e+00
  7.40136174e+00 1.38145898e+00 1.03183909e+00 3.64101867e+00
  1.76761392e+00 1.05452768e+01]
 [7.11743538e-01 1.46568596e+01 1.07430562e+01 7.46346659e+00
  3.52990930e+00 1.51836076e+01 7.05380274e+00 5.28360770e+00
  1.18466467e+01 2.05187122e+00]
 [2.12819180e+00 8.31488696e+00 5.78227829e+00 1.00601225e+01
  3.25589630e+00 9.39489409e+00 8.21385958e+00 1.23367955e+00
  4.97319729e+00 8.08196015e-01]
 [6.85527070e+00 1.44082353e+01 7.76834628e+00 2.01197594e-01
  3.50738479e+00 1.36269291e+01 4.61251158e-01 1.02051364e+01
  1.41535162e+01 4.48516900e+00]
 [2.87443845e-01 3.94850712e+00 1.13006544e+00 8.39302612e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [95]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [96]:
x = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(x)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [97]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [99]:
x = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
C = stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(C)

[[[[0 3 1]
   [1 2 0]
   [1 1 2]]

  [[3 1 3]
   [2 0 1]
   [1 2 2]]

  [[1 3 2]
   [0 1 0]
   [2 2 0]]

  [[3 2 4]
   [1 0 1]
   [2 0 0]]

  [[2 4 0]
   [0 1 4]
   [0 0 1]]

  [[4 0 2]
   [1 4 3]
   [0 1 2]]

  [[0 2 2]
   [4 3 4]
   [1 2 4]]

  [[2 2 3]
   [3 4 0]
   [2 4 2]]]


 [[[1 2 0]
   [1 1 2]
   [0 1 2]]

  [[2 0 1]
   [1 2 2]
   [1 2 3]]

  [[0 1 0]
   [2 2 0]
   [2 3 1]]

  [[1 0 1]
   [2 0 0]
   [3 1 1]]

  [[0 1 4]
   [0 0 1]
   [1 1 4]]

  [[1 4 3]
   [0 1 2]
   [1 4 0]]

  [[4 3 4]
   [1 2 4]
   [4 0 1]]

  [[3 4 0]
   [2 4 2]
   [0 1 2]]]


 [[[1 1 2]
   [0 1 2]
   [4 1 3]]

  [[1 2 2]
   [1 2 3]
   [1 3 4]]

  [[2 2 0]
   [2 3 1]
   [3 4 1]]

  [[2 0 0]
   [3 1 1]
   [4 1 3]]

  [[0 0 1]
   [1 1 4]
   [1 3 1]]

  [[0 1 2]
   [1 4 0]
   [3 1 2]]

  [[1 2 4]
   [4 0 1]
   [1 2 1]]

  [[2 4 2]
   [0 1 2]
   [2 1 1]]]


 [[[0 1 2]
   [4 1 3]
   [2 0 3]]

  [[1 2 3]
   [1 3 4]
   [0 3 3]]

  [[2 3 1]
   [3 4 1]
   [3 3 3]]

  [[3 1 1]
   [4 1 3]
   [3 3 2]]

  [[1 1 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [21]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S

Symetric([[ 3, 10,  5,  9,  8],
          [10,  1, 13,  4,  6],
          [ 5, 13,  8,  8, 11],
          [ 9,  4,  8,  6,  1],
          [ 8,  6, 11,  1,  4]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [20]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [19]:
r = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(r, np.arange(0, r.shape[0], k), axis=0),
                                       np.arange(0, r.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [18]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [17]:
M = np.arange(10000)
np.random.shuffle(M)
n = 5

# Slow
print (M[np.argsort(M)[-n:]])

# Fast
print (M[np.argpartition(-M,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9999 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [16]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7,8])))

[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 5 6]
 [3 5 7]
 [3 5 8]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [15]:
K = np.array([("GOOD", 2, 3),
              ("World", 0.5, 2)])
print(Z)
R = np.core.records.fromarrays(K.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[[0 1 0]
 [3 1 0]
 [1 3 4]
 [1 3 1]
 [1 4 4]
 [0 2 3]
 [0 4 3]
 [0 4 2]
 [3 2 0]
 [4 0 3]]
[(b'GOOD', 2. , 3) (b'World', 0.5, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [13]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.84 s ± 156 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
155 ms ± 34.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
125 ms ± 8.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [11]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [10]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 0]
 [3 1 0]
 [1 3 4]
 [1 3 1]
 [1 4 4]
 [0 2 3]
 [0 4 3]
 [0 4 2]
 [3 2 0]
 [4 0 3]]
[[0 1 0]
 [3 1 0]
 [1 3 4]
 [1 3 1]
 [1 4 4]
 [0 2 3]
 [0 4 3]
 [0 4 2]
 [3 2 0]
 [4 0 3]]
[[0 1 0]
 [3 1 0]
 [1 3 4]
 [1 3 1]
 [1 4 4]
 [0 2 3]
 [0 4 3]
 [0 4 2]
 [3 2 0]
 [4 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [9]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [8]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [7]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)
np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.57333558, 0.40918451, 0.6945053 , 0.14597474, 0.22061385],
       [0.23679374, 0.16899759, 0.28683814, 0.06028913, 0.09111589],
       [0.46837394, 0.33427432, 0.56736089, 0.11925087, 0.18022565],
       [0.03137023, 0.02238866, 0.03800007, 0.00798705, 0.01207095],
       [0.16038167, 0.11446297, 0.19427701, 0.04083415, 0.06171328]])

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
(hint: np.cumsum, np.interp)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.44292207, 0.0480825 , 0.13693653, 0.12412905, 0.43582305,
        0.27900389, 0.47228454, 0.44834292, 0.39886544, 0.47612833],
       [0.72804086, 0.07903428, 0.22508562, 0.20403367, 0.71637204,
        0.4586049 , 0.77630459, 0.73695122, 0.655624  , 0.78262272],
       [0.42303628, 0.04592375, 0.13078852, 0.11855605, 0.41625599,
        0.2664775 , 0.45108047, 0.42821375, 0.38095766, 0.45475169],
       [0.15268378, 0.01657497, 0.04720466, 0.04278968, 0.15023662,
        0.09617802, 0.16280559, 0.15455245, 0.13749661, 0.16413062],
       [0.71682366, 0.07781657, 0.22161764, 0.20089005, 0.70533464,
        0.451539  , 0.76434378, 0.72559674, 0.64552256, 0.77056456],
       [0.12397809, 0.01345875, 0.03832983, 0.0347449 , 0.12199101,
        0.07809584, 0.13219692, 0.12549544, 0.11164622, 0.13327284],
       [0.5177939 , 0.0562104 , 0.16008437, 0.1451119 , 0.50949486,
        0.32616688, 0.55211981, 0.52413109, 0.46628991, 0.55661336],
       [0.63683377, 0.06913307, 0.1968874

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [6]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
print(x,y,r)

[  0.           0.09950042   0.19601332   0.28660095   0.3684244
   0.43879128   0.49520137   0.53538953   0.55736537   0.55944897
   0.54030231   0.49895573   0.43482931   0.34774848   0.237954
   0.1061058   -0.04671924  -0.21903564  -0.40896377  -0.61425018
  -0.83229367  -1.06017682  -1.29470246  -1.53243485  -1.76974492
  -2.00285904  -2.22791076  -2.44099478  -2.63822255  -2.81577868
  -2.96997749  -3.09731897  -3.19454328  -3.25868324  -3.28711385
  -3.27759841  -3.2283303   -3.13797012  -3.00567731  -2.83113599
  -2.61457448  -2.35677818  -2.05909545  -1.72343644  -1.35226463
  -0.9485811   -0.51590162  -0.05822672   0.41999512   0.91391061
   1.41831093   1.92768649   2.43628669   2.93818398   3.42734153
   3.89768376   4.34316892   4.75786287   5.1360132    5.47212274
   5.76102172   5.99793747   6.178561     6.29910941   6.35638348
   6.34781957   6.27153511   6.12636709   5.91190293   5.62850319
   5.27731578   4.86028133   4.38012946   3.84036588   3.24525022
   2.59976488

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [5]:
X = np.asarray([[1.0, 2.0, 3.0, 4.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 3.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [2]:
import numpy as np
X = np.random.randn(27) # random 1D array
N = 279 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.31874683  0.23846493]
